
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAILED = 'LOGOUT_USER_FAILED';

export const REQUESTED_NEWS = 'REQUESTED_NEWS';
export const REQUESTED_NEWS_SUCCEEDED = 'REQUESTED_NEWS_SUCCEEDED';
export const REQUESTED_NEWS_FAILED = 'REQUESTED_NEWS_FAILED';
export const FETCHED_NEWS = 'FETCHED_NEWS';

export const REQUESTED_CARS = 'REQUESTED_CARS';
export const REQUESTED_CARS_SUCCEEDED = 'REQUESTED_CARS_SUCCEEDED';
export const REQUESTED_CARS_FAILED = 'REQUESTED_CARS_FAILED';
export const FETCHED_CARS = 'FETCHED_CARS';

export const ADD_CAR = 'ADD_CAR';
export const ADD_CAR_SUCCESS = 'ADD_CAR_SUCCESS';
export const ADD_CAR_FAILED = 'ADD_CAR_FAILED';
